pipeline {
	agent any
	stages {
		stage('Init') {
			steps {
				echo 'Hi This is VJ'
				echo 'We are starting Testing'
			}
		}
		stage('Build') {
			steps {
				echo 'Building Sample Maven Project'
			}
		}
		stage('Deploy') {
			steps {
				echo 'Deploying in Staging Area'
			}
		}
		
		stage('Deploy in Quality Assurance') {
			steps {
				echo 'Deploying in Quality Assurance'
			}
		}
		stage('Deploy Production') {
			steps {
				echo 'Deploy in Production Area'
			}
		}
	}
}
